import React from 'react'
import '../App.css'

const NavbarController = () => {
    return (
        <div className='navbar-controller'>
            <ul>
                <li>
                    <div className='img'></div>
                </li>
                <li>
                    <small className='small-text'> @generated by Purplai</small>
                </li>
            </ul>
        </div>
    )
}

export default NavbarController